name: Watch for changes and recompile on change

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  background-watch-and-recompile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.6'
      - name: Start Java compile watcher
        uses: JarvusInnovations/background-action@v1
        with:
          run: mvn -V -B -ntp fizzed-watcher:run > watcher-output.txt 2>&1 &
          tail: true
          log-output-resume: false
          wait-on: watcher-output.txt # Wait until it no longer changes -> it's running
          log-output: false
          log-output-if: false
      - run: mvn -V -B -ntp clean install
      - name: Test Java compile
        run: |
          ls -la --time-style=full-iso src/main/java/org/vaadin/example/Application.java
          ls -la --time-style=full-iso target/classes/org/vaadin/example/Application.class
          sleep 1
          echo "// Foo" >> src/main/java/org/vaadin/example/Application.java
          sleep 30
          ls -la --time-style=full-iso src/org/vaadin/example/Application.java
          ls -la --time-style=full-iso target/org/vaadin/example/Application.class
          ps axu