# Example of skipping build action based on commit message content

name: Skip formatter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # from https://github.com/orgs/community/discussions/28474#discussioncomment-3350256
  check_skip_flags:
    name: Check skip flags
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    steps:
      - name: Get repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"

  # can be skipped when we want only to update formatter
  build:
    needs: check_skip_flags
    if: ${{ !contains(needs.check_skip_flags.outputs.head-commit-message, '[formatter]') }}   
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo 'Running build...'


  # always run formatter check
  formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Formatter
        run: echo 'Running maven formatter:format...'
