name: Build project on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.3'
      - uses: stCarolas/setup-maven@v5
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - uses: nanasess/setup-chromedriver@master
      - name: Run Chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --help
          chromedriver --binary=${{ steps.setup-chrome.outputs.chrome-path }} --url-base=/wd/hub --no-sandbox --disable-extensions --headless --disable-gpu --disable-dev-shm-usage --window-size=1280,1024 &
      - run: mvn -V -B -ntp -e -fae install
      - run: mvn -V -B -ntp -e -fae verify
