name: ChromeDriver playground

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - uses: nanasess/setup-chromedriver@master
    - name: Run Chromedriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub --no-sandbox --disable-extensions --headless --disable-gpu --disable-dev-shm-usage --window-size=1280,1024 &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
