name: Use HotSwap on GH Actions

env:
  JBR_VERSION: 'jbr_jcef-21.0.3-linux-x64-b509.4'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hotswap:
    runs-on: ubuntu-latest
    steps:
      - name: Download and extract JBR
        run: |
          wget -q https://cache-redirector.jetbrains.com/intellij-jbr/${JBR_VERSION}.tar.gz
          tar -xzf ${JBR_VERSION}.tar.gz
      - name: Set ENV vars
        run: |
          echo "JAVA_HOME=`pwd`/${JBR_VERSION}" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
      - run: |
          java --version
          javac --version
      # - uses: stCarolas/setup-maven@v5
      #   with:
      #     maven-version: '3.9.6'
