name: Use HotSwap on GH Actions

env:
  MAVEN_OPTS: "-XX:+AllowEnhancedClassRedefinition -XX:HotswapAgent=fatjar"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hotswap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          download_url="https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-21.0.3-linux-x64-b509.4.tar.gz"
          wget -q -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '21.0.3'
          architecture: x64
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.6'
      - name: Check Java version
        run: |
          java --version
          javac --version
      - name: Run using JBR
        run: mvn -V -B -ntp package spring-boot:run
