name: Use inotify to watch file changes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  inotify:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get -y install inotify-tools
      - uses: actions/checkout@v4
      - run: |
          chmod +x scripts/watcher.sh
          ./scripts/watcher.sh src/main/java watcher.log
          echo "// test" >> src/main/java/org/vaadin/example/MainView.java
      - run: |
          cat watcher.log
          kill `cat watcher.pid`
