name: Use inotify to watch file changes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  inotify:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get -y install inotify-tools
      - uses: actions/checkout@v4
      - name: Start inotify watcher
        uses: JarvusInnovations/background-action@v1
        with:
          run: scripts/watcher.sh
          wait-on: watcher-output.txt # Wait until it no longer changes -> it's running
          wait-for: 10m
          log-output: false
          log-output-if: false
      - run: |
          cat watcher.pid
          sleep 10
          kill `cat watcher.pid`
          cat watcher-output.txt
